In [11]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ebteshamul\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ebteshamul\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 16.9 MB/s eta 0:00:01
   ------ --------------------------------- 1.6/9.7 MB 3.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.7 MB 3.3 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.7 MB 3.0 MB/s eta 0:00:03
   ------------- -------------------------- 3.1/9.7 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.7 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.7 MB 2.8 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.7 MB 2.7 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.7 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.7 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.7 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 6.8/9.7 MB 2.6 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.7 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.7 MB 2.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.5 MB/s eta 0:00:00
Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 2.4 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.6 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/12.6 MB 2.5 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.6 MB 2.5 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.6 MB 2.5 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.6 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.6 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.6 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 4.7/12.6 MB 2.5 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.6 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.6 MB 2.5 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.6 MB 2.5 MB/s eta 0:00:03
   ----------------------- ---------------- 7.3/12.6 MB 2.5 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.6 MB 2.5 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 2.5 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 2.5 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 2.5 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.6 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 2.4 MB/s eta 0:00:00
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.4 pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\Ebteshamul\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [12]:
import pandas as pd

In [14]:
df = pd.read_csv('customer_churn_exam_dataset_3500.csv')

In [25]:
df.head(20)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,__4__,0,46.1,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,27.2,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,25.1,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49.0,Monthly,Cash,No,3,25,0,3,1
5,C0006,36,Female,East,Standard,47.99,11,0,36.8,3,Card,Yes,8,0,2,3,0
6,C0007,28,Female,West,Standard,37.51,64,2,40.2,Quarterly,NaN,Yes,5,10,2,3,0
7,C0008,58,Male,Central,Standard,37.32,13,4,50.6,3,Bank Transfer,Yes,5,13,4,2,0
8,C0009,26,Male,East,Premium,69.6,33,1,57.3,Yearly,Cash,Yes,6,1,2,2,0
9,C0010,23,Male,Central,Standard,43.56,5,0,37.6,Monthly,Card,No,5,0,0,2,0
10,C0011,29,Male,South,Basic,27.07,23,5,42.2,Monthly,Card,Yes,4,20,0,1,0
11,C0012,29,Female,West,Basic,15.25,2,3,46.1,Monthly,UPI,No,6,9,0,2,0
12,C0013,37,Male,West,Basic,__23.2__,12,5,37.7,Yearly,UPI,NaN,4,3,1,2,0
13,C0014,37,Female,West,Premium,83.14,4,4,53.1,Yearly,UPI,Yes,4,0,"""""",2,0
14,C0015,39,Male,Central,Basic,23.21,7,7,44.1,Yearly,Bank Transfer,Yes,1,18,1,2,0
15,C0016,18,Female,Central,Standard,52.84,18,0,"""49.1""",Monthly,Cash,Yes,6,0,0,3,0
16,C0017,29,Male,West,Standard,54.22,15,4,"""49.0""",Monthly,__value__,Yes,__6__,11,0,3,0
17,C0018,26,Female,Central,Basic,39.74,31,NaN,56.5,Yearly,Card,Yes,__7__,12,0,3,0
18,C0019,41,Male,West,Basic,28.87,43,8,44.9,Yearly,Card,Yes,7,27,1,3,0
19,C0020,32,Female,South,Standard,40.54,33,1,38.7,Monthly,Card,No,7,0,1,2,0

here Custorem id has to be dropped cuz we can use the index number
many datas are in double dashes, gotta fix those
and most of then are in strings. many need to be in floot or int (before encoding i guess)
handle nan values
visualise
encode

In [17]:
df.shape

(3500, 17)

In [18]:
df.isna().sum()

CustomerID               0
Age                     53
Gender                  55
Region                  33
PlanType                43
MonthlyCharges          76
TenureMonths            39
SupportTickets          43
AvgMonthlyUsageHours    73
ContractType            47
PaymentMethod           39
AutoPay                 44
SatisfactionScore       57
LastLoginDays           28
ReferralCount           19
DeviceCount             24
Churn                    0
dtype: int64

In [23]:
df.dtypes

CustomerID                str
Age                       str
Gender                    str
Region                    str
PlanType                  str
MonthlyCharges            str
TenureMonths              str
SupportTickets            str
AvgMonthlyUsageHours      str
ContractType              str
PaymentMethod             str
AutoPay                   str
SatisfactionScore         str
LastLoginDays             str
ReferralCount             str
DeviceCount               str
Churn                   int64
dtype: object

In [26]:
df.head(1)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0

In [29]:
df = df.drop("CustomerID", axis = 1)

In [31]:
df = df.map(lambda x: x.strip('__') if isinstance(x,str) else x)

In [34]:
df.head(2)

,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,35,Male,South,Basic,16.62,2,5,27.0,Quarterly,Card,Yes,4,26,0,1,0
1,26,Male,North,Standard,46.23,4,0,46.1,Monthly,UPI,Yes,5,11,0,2,1

In [39]:
df['TenureMonths'].value_counts()

TenureMonths
1     206
2     172
4     166
3     164
5     131
     ...
65      4
58      4
71      3
68      3
69      2
Name: count, Length: 75, dtype: int64