In [22]:
#%pip install pandas

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('customer_churn_exam_dataset_3500.csv')

In [25]:
df.head(20)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,__4__,0,46.1,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,27.2,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,25.1,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49.0,Monthly,Cash,No,3,25,0,3,1
5,C0006,36,Female,East,Standard,47.99,11,0,36.8,3,Card,Yes,8,0,2,3,0
6,C0007,28,Female,West,Standard,37.51,64,2,40.2,Quarterly,NaN,Yes,5,10,2,3,0
7,C0008,58,Male,Central,Standard,37.32,13,4,50.6,3,Bank Transfer,Yes,5,13,4,2,0
8,C0009,26,Male,East,Premium,69.6,33,1,57.3,Yearly,Cash,Yes,6,1,2,2,0
9,C0010,23,Male,Central,Standard,43.56,5,0,37.6,Monthly,Card,No,5,0,0,2,0
10,C0011,29,Male,South,Basic,27.07,23,5,42.2,Monthly,Card,Yes,4,20,0,1,0
11,C0012,29,Female,West,Basic,15.25,2,3,46.1,Monthly,UPI,No,6,9,0,2,0
12,C0013,37,Male,West,Basic,__23.2__,12,5,37.7,Yearly,UPI,NaN,4,3,1,2,0
13,C0014,37,Female,West,Premium,83.14,4,4,53.1,Yearly,UPI,Yes,4,0,"""""",2,0
14,C0015,39,Male,Central,Basic,23.21,7,7,44.1,Yearly,Bank Transfer,Yes,1,18,1,2,0
15,C0016,18,Female,Central,Standard,52.84,18,0,"""49.1""",Monthly,Cash,Yes,6,0,0,3,0
16,C0017,29,Male,West,Standard,54.22,15,4,"""49.0""",Monthly,__value__,Yes,__6__,11,0,3,0
17,C0018,26,Female,Central,Basic,39.74,31,NaN,56.5,Yearly,Card,Yes,__7__,12,0,3,0
18,C0019,41,Male,West,Basic,28.87,43,8,44.9,Yearly,Card,Yes,7,27,1,3,0
19,C0020,32,Female,South,Standard,40.54,33,1,38.7,Monthly,Card,No,7,0,1,2,0

here Custorem id has to be dropped cuz we can use the index number
many datas are in double dashes, gotta fix those
and most of then are in strings. many need to be in floot or int (before encoding i guess)
handle nan values
visualise
encode

In [26]:
df.shape

(3500, 17)

In [27]:
df.isna().sum()

CustomerID               0
Age                     53
Gender                  55
Region                  33
PlanType                43
MonthlyCharges          76
TenureMonths            39
SupportTickets          43
AvgMonthlyUsageHours    73
ContractType            47
PaymentMethod           39
AutoPay                 44
SatisfactionScore       57
LastLoginDays           28
ReferralCount           19
DeviceCount             24
Churn                    0
dtype: int64

In [28]:
df.dtypes

CustomerID                str
Age                       str
Gender                    str
Region                    str
PlanType                  str
MonthlyCharges            str
TenureMonths              str
SupportTickets            str
AvgMonthlyUsageHours      str
ContractType              str
PaymentMethod             str
AutoPay                   str
SatisfactionScore         str
LastLoginDays             str
ReferralCount             str
DeviceCount               str
Churn                   int64
dtype: object

In [29]:
df.head(1)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0

In [30]:
df = df.drop("CustomerID", axis = 1)

In [31]:
df = df.map(lambda x: x.strip('__') if isinstance(x,str) else x)

In [32]:
df.head(2)

,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,35,Male,South,Basic,16.62,2,5,27.0,Quarterly,Card,Yes,4,26,0,1,0
1,26,Male,North,Standard,46.23,4,0,46.1,Monthly,UPI,Yes,5,11,0,2,1

In [40]:
#df.isna().sum()

In [42]:
num_cols = ['Age', 'TenureMonths', 'MonthlyCharges', 'SupportTickets', 'AvgMonthlyUsageHours', 'SatisfactionScore','LastLoginDays', 'ReferralCount', 'DeviceCount' ]
for col in num_cols:
    df[col]= pd.to_numeric(df[col], errors='coerce')

fillna_mean_target = ['TenureMonths', 'Age', 'SupportTickets', 'AvgMonthlyUsageHours', 'SatisfactionScore', 'ReferralCount', 'DeviceCount' ]
df[fillna_mean_target] = df[fillna_mean_target].fillna(df[fillna_mean_target].mean())   

fillna_median = ['MonthlyCharges', 'LastLoginDays',]
df[fillna_median] = df[fillna_median].fillna(df[fillna_median].median())

In [43]:
df.isna().sum()

Age                      0
Gender                  55
Region                  33
PlanType                43
MonthlyCharges           0
TenureMonths             0
SupportTickets           0
AvgMonthlyUsageHours     0
ContractType            47
PaymentMethod           39
AutoPay                 44
SatisfactionScore        0
LastLoginDays            0
ReferralCount            0
DeviceCount              0
Churn                    0
dtype: int64